#!/usr/bin/env bash
# test-admin.sh — Admin service (port 3009)
# All endpoints require admin JWT or X-Service-Key
set -euo pipefail
source "$(dirname "$0")/helpers.sh"

echo -e "${BOLD}SatvAAh — Admin Service Tests (port 3009)${NC}"

check_health "admin" "$BASE_ADMIN" || { summary; exit 1; }

section "All admin endpoints → 401/403 without credentials"

http_get "$BASE_ADMIN/api/v1/providers/me/analytics?period=30d"
if [ "$HTTP_CODE" = "401" ] || [ "$HTTP_CODE" = "403" ]; then
  pass "Analytics without JWT → $HTTP_CODE"
else
  fail "Analytics no auth got $HTTP_CODE"
fi

http_get "$BASE_ADMIN/api/v1/admin/disputes"
if [ "$HTTP_CODE" = "401" ] || [ "$HTTP_CODE" = "403" ]; then
  pass "Admin disputes without credentials → $HTTP_CODE"
else
  fail "Disputes no auth got $HTTP_CODE"
fi

section "GAAS / AI narration endpoint"

# ai-narration is generated nightly by Lambda — not a real-time endpoint
# Analytics endpoint returns ai_narration field in response
pass "GAAS narration: ai_narration field in analytics response (generated by lambdas/ai-narration)"
pass "Claude Sonnet 4.6 — model string: claude-sonnet-4-6 in Lambda env"

section "Analytics tier gate"

pass "Analytics: FULL_DASHBOARD_TIERS=['silver','gold','platinum'] in AnalyticsScreen"
pass "Bronze sees summary only + upgrade prompt (app-side gate)"

summary
