#!/usr/bin/env python3
"""
scripts/generate_synonyms.py

Generates 8 multilingual synonyms for all 1555 taxonomy nodes using Claude API.
Synonyms: 3 English variants + Hindi + Telugu + Tamil + Marathi + Punjabi

Run: python3 scripts/generate_synonyms.py --key sk-ant-YOUR_KEY
     python3 scripts/generate_synonyms.py --key sk-ant-YOUR_KEY --batch 10 --resume

Output: packages/db/prisma/migrations/V052_search_synonyms/migration.sql
"""

import json, re, time, argparse, os, sys
try:
    import requests
except ImportError:
    os.system(f"{sys.executable} -m pip install requests -q")
    import requests

MIGRATION_DIR = "packages/db/prisma/migrations/V052_search_synonyms"
PROGRESS_FILE = "/tmp/synonym_progress.json"
SEED_FILE = "packages/db/prisma/migrations/V046_seed_taxonomy/migration.sql"

# ── Extract nodes from seed ────────────────────────────────────────────────────
def load_nodes():
    with open(SEED_FILE) as f:
        content = f.read()
    pattern = r"\('([\w-]+)',\s*'([^']+)',\s*'([^']+)',\s*'([^']+)',\s*'([^']+)',\s*\n?\s*'([^']+)',\s*'[^']+',\s*'(services|products|expertise|establishments)'"
    matches = re.findall(pattern, content)
    nodes = []
    for m in matches:
        node_id, l1, l2, l3, l4, display_name, tab = m
        nodes.append({'id': node_id, 'display_name': display_name,
                      'l1': l1, 'l2': l2, 'l3': l3, 'l4': l4, 'tab': tab})
    return nodes

# ── Claude API call ────────────────────────────────────────────────────────────
def generate_batch(api_key, nodes):
    node_list = '\n\n'.join([
        f"{i+1}. ID: {n['id']}\n   Name: \"{n['display_name']}\"\n   Category: {n['l1']} > {n['l2']} > {n['l3']}\n   Tab: {n['tab']}"
        for i, n in enumerate(nodes)
    ])

    prompt = f"""You are generating multilingual search synonyms for SatvAAh — an Indian local services marketplace.

For each of the {len(nodes)} nodes below, generate EXACTLY 8 synonyms:
1. English variant 1 (most common alternate name)
2. English variant 2 (abbreviated or informal)
3. English variant 3 (another common search term)
4. Hindi (use common words people type, e.g. "bijli wala", "nai", "mali")
5. Telugu (transliterated Roman, e.g. "vidyut pani", "kurralu")
6. Tamil (transliterated Roman, e.g. "azhuku thozhi", "maram")
7. Marathi (use common Marathi words people type)
8. Punjabi (use common Punjabi words people type)

Rules:
- Keep each synonym under 60 characters
- Use terms real Indian consumers type when searching
- Services: name the WORKER (nai=barber, mali=gardener, darzi=tailor)
- Products: name what BUYERS search for
- Establishments: name how locals refer to the place
- No formal/academic language — use street-level vocabulary
- Return ONLY valid JSON, zero other text

JSON format:
{{
  "synonyms": [
    {{
      "id": "node_uuid_here",
      "synonyms": "en1, en2, en3, hindi_term, telugu_term, tamil_term, marathi_term, punjabi_term"
    }}
  ]
}}

Nodes:
{node_list}"""

    r = requests.post(
        'https://api.anthropic.com/v1/messages',
        headers={'Content-Type': 'application/json', 'x-api-key': api_key,
                 'anthropic-version': '2023-06-01'},
        json={'model': 'claude-haiku-4-5-20251001', 'max_tokens': 4000,
              'messages': [{'role': 'user', 'content': prompt}]},
        timeout=60
    )

    if r.status_code != 200:
        raise Exception(f"API error {r.status_code}: {r.text[:200]}")

    data = r.json()
    text = data['content'][0]['text']
    clean = text.replace('```json', '').replace('```', '').strip()
    return json.loads(clean)

# ── Load/save progress ─────────────────────────────────────────────────────────
def load_progress():
    if os.path.exists(PROGRESS_FILE):
        with open(PROGRESS_FILE) as f:
            return json.load(f)
    return {}

def save_progress(results):
    with open(PROGRESS_FILE, 'w') as f:
        json.dump(results, f)

# ── Write SQL migration ────────────────────────────────────────────────────────
def write_sql(results):
    os.makedirs(MIGRATION_DIR, exist_ok=True)
    path = f"{MIGRATION_DIR}/migration.sql"
    lines = [
        "-- V052: Multilingual search synonyms for all 1555 taxonomy nodes",
        "-- Auto-generated by scripts/generate_synonyms.py",
        "-- 8 synonyms per node: 3 English + Hindi + Telugu + Tamil + Marathi + Punjabi",
        f"-- Total nodes: {len(results)}",
        "BEGIN;",
        ""
    ]
    for node_id, synonyms in results.items():
        safe = synonyms.replace("'", "''")
        lines.append(f"UPDATE taxonomy_nodes SET search_synonyms = '{safe}', updated_at = NOW() WHERE id = '{node_id}'::uuid;")
    lines.extend([
        "",
        "COMMIT;",
        "",
        "-- Verify",
        "SELECT COUNT(*) as nodes_with_synonyms FROM taxonomy_nodes WHERE search_synonyms IS NOT NULL;"
    ])
    with open(path, 'w') as f:
        f.write('\n'.join(lines))
    return path

# ── Main ───────────────────────────────────────────────────────────────────────
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--key', required=True, help='Anthropic API key (sk-ant-...)')
    ap.add_argument('--batch', type=int, default=10, help='Nodes per API call (default 10)')
    ap.add_argument('--resume', action='store_true', help='Resume from last checkpoint')
    ap.add_argument('--tab', default='all', help='Filter by tab: services/expertise/establishments/products/all')
    args = ap.parse_args()

    print('=' * 65)
    print('  SatvAAh Taxonomy Synonym Generator')
    print('  8 languages × 1555 nodes = 12,440 synonyms')
    print('=' * 65)

    # Load nodes
    print('\n[1] Loading taxonomy nodes...')
    all_nodes = load_nodes()
    if args.tab != 'all':
        all_nodes = [n for n in all_nodes if n['tab'] == args.tab]
    print(f'    {len(all_nodes)} nodes to process')

    # Load existing progress
    results = {}
    if args.resume:
        results = load_progress()
        print(f'    Resuming — {len(results)} already done')

    # Filter out already processed
    pending = [n for n in all_nodes if n['id'] not in results]
    print(f'    {len(pending)} pending')

    if not pending:
        print('    All done!')
    else:
        print(f'\n[2] Generating synonyms in batches of {args.batch}...')
        print(f'    Model: claude-haiku (fast + cheap)')
        est_calls = len(pending) // args.batch + 1
        print(f'    Est. API calls: ~{est_calls}')
        print()

        t0 = time.time()
        done = 0
        errors = 0

        for i in range(0, len(pending), args.batch):
            batch = pending[i:i + args.batch]
            pct = int((i + len(batch)) / len(pending) * 100)

            try:
                result = generate_batch(args.key, batch)
                for item in result.get('synonyms', []):
                    results[item['id']] = item['synonyms']
                    done += 1

                # Sample output
                if result.get('synonyms'):
                    sample = result['synonyms'][0]
                    node = batch[0]
                    print(f'  [{pct:3d}%] {node["display_name"][:35]:<35} → {sample["synonyms"][:60]}')

                save_progress(results)
                time.sleep(0.3)  # Rate limit

            except json.JSONDecodeError as e:
                errors += 1
                print(f'  [{pct:3d}%] JSON parse error — skipping batch ({e})')
                time.sleep(2)
            except Exception as e:
                errors += 1
                print(f'  [{pct:3d}%] Error: {e}')
                if 'rate_limit' in str(e).lower() or '429' in str(e):
                    print('    Rate limited — waiting 60s...')
                    time.sleep(60)
                else:
                    time.sleep(3)

    # Write SQL
    print(f'\n[3] Writing SQL migration...')
    path = write_sql(results)
    elapsed = time.time() - t0 if pending else 0

    print(f'\n{"=" * 65}')
    print(f'  Done in {elapsed:.0f}s')
    print(f'  Synonyms generated: {len(results)}')
    print(f'  Errors: {errors if pending else 0}')
    print(f'  SQL written to: {path}')
    print(f'\n  Apply to DB:')
    print(f'  docker exec -i satvaaah-postgres psql -U satvaaah_user -d satvaaah < {path}')
    print(f'{"=" * 65}\n')

if __name__ == '__main__':
    main()
