/**
 * SearchNarrationBanner.tsx
 * SatvAAh — Phase 25 · Shared UI Components
 *
 * Saffron background banner that explains why the search ring expanded
 * (3 km → 7 km → 15 km → 50 km → 150 km).
 * Text is generated by the backend GAAS narration; falls back to template.
 *
 * Slides down from above on appearance.
 */

import React, { useEffect, useRef } from 'react';
import {
  Animated,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';

const SAFFRON    = '#C8691A';
const SAFFRON_BG = '#FDF0E6';
const DEEP_INK   = '#1C1C2E';

// Ring expansion radii (km) matching backend search config
const RING_LABELS: Record<number, string> = {
  3:   '3 km',
  7:   '7 km',
  15:  '15 km',
  50:  '50 km',
  150: '150 km',
};

// ─── Props ────────────────────────────────────────────────────────────────────
interface SearchNarrationBannerProps {
  radiusKm:      number;    // current ring radius
  resultCount:   number;    // how many results found at this radius
  searchQuery:   string;
  /** AI-generated narration from GAAS; falls back to template if not provided */
  narrationText?: string;
  onDismiss?:    () => void;
  visible?:      boolean;
}

// ─── Component ────────────────────────────────────────────────────────────────
const SearchNarrationBanner: React.FC<SearchNarrationBannerProps> = ({
  radiusKm,
  resultCount,
  searchQuery,
  narrationText,
  onDismiss,
  visible = true,
}) => {
  const slideAnim = useRef(new Animated.Value(-80)).current;
  const opacAnim  = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    if (visible) {
      Animated.parallel([
        Animated.spring(slideAnim, {
          toValue: 0, tension: 60, friction: 10, useNativeDriver: true,
        }),
        Animated.timing(opacAnim, {
          toValue: 1, duration: 250, useNativeDriver: true,
        }),
      ]).start();
    } else {
      Animated.parallel([
        Animated.timing(slideAnim, {
          toValue: -80, duration: 220, useNativeDriver: true,
        }),
        Animated.timing(opacAnim, {
          toValue: 0, duration: 200, useNativeDriver: true,
        }),
      ]).start();
    }
  }, [visible]); // eslint-disable-line

  const ringLabel = RING_LABELS[radiusKm] ?? `${radiusKm} km`;

  const defaultNarration =
    radiusKm <= 3
      ? `${resultCount} trusted ${searchQuery} providers within ${ringLabel} of you`
      : `Expanded search to ${ringLabel} — found ${resultCount} trusted providers for "${searchQuery}"`;

  const text = narrationText ?? defaultNarration;

  return (
    <Animated.View
      style={[
        styles.banner,
        { transform: [{ translateY: slideAnim }], opacity: opacAnim },
      ]}
      pointerEvents={visible ? 'auto' : 'none'}
    >
      {/* Ring pulse icon */}
      <View style={styles.iconWrap}>
        <View style={styles.ringOuter}>
          <View style={styles.ringInner} />
        </View>
      </View>

      <View style={styles.content}>
        {radiusKm > 3 && (
          <View style={styles.expansionBadge}>
            <Text style={styles.expansionLabel}>Ring expanded · {ringLabel}</Text>
          </View>
        )}
        <Text style={styles.narration} numberOfLines={3}>{text}</Text>
      </View>

      {onDismiss && (
        <TouchableOpacity
          onPress={onDismiss}
          hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
        >
          <Text style={styles.dismiss}>✕</Text>
        </TouchableOpacity>
      )}
    </Animated.View>
  );
};

// ─── Styles ───────────────────────────────────────────────────────────────────
const styles = StyleSheet.create({
  banner: {
    flexDirection:    'row',
    alignItems:       'center',
    backgroundColor:  SAFFRON_BG,
    borderLeftWidth:  4,
    borderLeftColor:  SAFFRON,
    marginHorizontal: 16,
    marginTop:        8,
    borderRadius:     12,
    padding:          12,
    gap:              10,
    shadowColor:      SAFFRON,
    shadowOffset:     { width: 0, height: 2 },
    shadowOpacity:    0.15,
    shadowRadius:     6,
    elevation:        3,
  },
  iconWrap: {
    alignItems:     'center',
    justifyContent: 'center',
    flexShrink:     0,
  },
  ringOuter: {
    width:          28,
    height:         28,
    borderRadius:   14,
    borderWidth:    2,
    borderColor:    SAFFRON + '60',
    alignItems:     'center',
    justifyContent: 'center',
  },
  ringInner: {
    width:           14,
    height:          14,
    borderRadius:    7,
    borderWidth:     2,
    borderColor:     SAFFRON,
  },
  content: {
    flex: 1,
    gap:  3,
  },
  expansionBadge: {
    alignSelf:        'flex-start',
    backgroundColor:  SAFFRON + '20',
    borderRadius:     6,
    paddingHorizontal: 7,
    paddingVertical:   2,
  },
  expansionLabel: {
    fontFamily: 'PlusJakartaSans-SemiBold',
    fontSize:   10,
    color:      SAFFRON,
    letterSpacing: 0.3,
  },
  narration: {
    fontFamily: 'PlusJakartaSans-Regular',
    fontSize:   13,
    color:      DEEP_INK,
    lineHeight: 18,
  },
  dismiss: {
    fontSize:   13,
    color:      SAFFRON + '80',
    flexShrink: 0,
  },
});

export default SearchNarrationBanner;
