-- V052: Multilingual search synonyms for all 1555 taxonomy nodes
-- Auto-generated by scripts/generate_synonyms.py
-- 8 synonyms per node: 3 English + Hindi + Telugu + Tamil + Marathi + Punjabi
-- Total nodes: 0
BEGIN;


COMMIT;

-- Verify
SELECT COUNT(*) as nodes_with_synonyms FROM taxonomy_nodes WHERE search_synonyms IS NOT NULL;